# Generated by Django 4.0.4 on 2022-05-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user',
            new_name='owner',
        ),
    ]
