# Generated by Django 4.0.4 on 2022-05-03 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SALARY', 'SALARY'), ('COMMISSIONS', 'COMMISSIONS'), ('PASSIVE JOBS', 'PASSIVE JOBS'), ('OTHER', 'OTHER')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, max_length=225)),
                ('date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
